### ISSUE TITLE
report section for empty responses

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#161]
I've just done a scan and got back a load of responses that have a 0 length content. it would be good to group these in their own section at the end of the report.

**Comment by ChrisTruncer** [comment]
@rvazarkar any chance you might be able to look at this?

**Comment by ChrisTruncer** [comment]
can you give me a sample site that has this?

**Comment by digininja** [comment]
Probably. Basically it's when the content length is 0 if you can detect that

**Comment by Relkci** [comment]
I'm not exactly sure when this was implemented, but it works today. 

![image](https://github.com/RedSiege/EyeWitness/assets/29710634/eb807888-c8e4-4253-8be0-06f05dfd786f)
