### ISSUE TITLE
raw_input left over from Python3 migration

### ISSUE THREAD

**Issue by Chiggins** [RedSiege/EyeWitness#427]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali Linux x64

Source commit 3c15226c59dcc2d8669fa0b89323ded358594c12

## Pastebin link to error you are encountering

```
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Traceback (most recent call last):
  File "EyeWitness.py", line 424, in <module>
    cli_parsed = create_cli_parser()
  File "EyeWitness.py", line 153, in create_cli_parser
    overwrite_dir = raw_input(('Directory Exists! Do you want to '
NameError: name 'raw_input' is not defined
```

## Expected behavior (vs. what you encountered)

Should've prompted if I wanted to overwrite the existing directory

## Any additional information

```
╰─± ag raw_input
EyeWitness.py
153:                    overwrite_dir = raw_input(('Directory Exists! Do you want to '

MiktoList.py
18:                response = raw_input().lower()

Recategorize.py
19:                response = raw_input().lower()

Search.py
19:                response = raw_input().lower()
```

Also [PEP-3111](https://www.python.org/dev/peps/pep-3111/)

**Comment by ChrisTruncer** [comment]
I've pushed a patch to fix the issue in EyeWitness.py, but I have yet to completely move the other scripts from Py 2 to 3. I will get that done shortly, and I'll leave this open in the meantime until I complete that. Thanks for sending this over.
