### ISSUE TITLE
Feature Request - ssdeep / CSV report

### ISSUE THREAD

**Issue by BeanBagKing** [RedSiege/EyeWitness#503]
I'm sorting through ~2500 assets in our environment and trying to find an easier way of saying "give me all of X" without visually looking at every screenshots. One thing that seems to work well on a number of these devices is an [ssdeep](https://ssdeep-project.github.io/ssdeep/index.html) hash of the page. Devices that might have a <device ip is> field, MAC Address, or timestamp still have roughly the same hash.

Which also brings me to CSV output. I'm sorry if this is a thing already, but I don't see it in the output options. I also know that at face value this seems like a contradiction for EyeWitness, a program specifically designed to give you a visual representation. However, with the massive pile of assets, it's a whole lot easier to sort a CSV by page title or server than it is to find systems I need visually. More importantly, between this and ssdeep, it would be really easy to run a report that gives me all devices with a <80% similarity of a known device.

Alternatively, if you can give me a push in the right direction on the SQL database, I can write my own query. I did try to browse this, but it appears everything is in blob form. Or I'm just looking in the wrong place. I'm not sure what the structure looks like.

I've been trying to write this myself, but have been having a lot of problems with getting the actual page that should be rendered after running into javascript redirects, meta refresh, pages not rendering without JavaScript, the list goes on. EyeWitness has 90% of what I need already.

**Comment by ChrisTruncer** [comment]
EyeWitness SHOULD output CSV for you, but it doesn't contain all the details that you are requesting (this is the Python version of EyeWitness which generates the CSV).

I can look into generating a ssdeep hash of the images too. That shouldn't be too hard. I don't know that I can get this done immediately, but I'm open to getting this added in.

**Comment by BeanBagKing** [comment]
You would want an ssdeep hash of the html result, not the images (some feedback on that [here](https://github.com/ssdeep-project/ssdeep/issues/17)). 

I don't seem to get a CSV when running it, if that's what you're talking about
```
Attempting to screenshot http://10.0.0.43

[*] Done! Report written in the /home/user/EyeWitness/Python/09112020_105138 folder!
Would you like to open the report now? [Y/n]
```

and there isn't one that I see in the resulting folder:
```
$ ls
jquery-1.11.3.min.js  report.html  screens  source  style.css
```

I have no need for this immediately, I just know it would be helpful in my case, and thought it might be helpful to others as well.

**Comment by 0x6d6f7468** [comment]
This is a really old thread, but it's sounding like we might still want a more robust CSV output of the results, not just the requests.

I don't think this should be too difficult to put together. The current idea is to put a handful of fields in the report. Rather than doing a hash of page source or screenshot, I think we could just as well include fields for hostname, page title, category, etc. and then be able to parse on that.
