### ISSUE TITLE
UserAgent Cycling Function/Parameter not Enabled

### ISSUE THREAD

**Issue by WebBreacher** [RedSiege/EyeWitness#530]
Looks like the `get_ua_values(cycle_value)` https://github.com/FortyNorthSecurity/EyeWitness/blob/be5618142468ec9f17747627bf9668946b16aa4b/Python/modules/helpers.py#L477 function that governs cycling through different user agents is not referenced in the program any more. The function exists but there is no place to "turn it on" (like `--cycle mobile`) and use the feature. 

Any chance we can get it turned back on?

**Comment by TheProdigyLeague** [comment]
for, context:
@ChrisTruncer 
f(x)get_method_server, if "issue" ["OPEN"]::return, ["CLOSE"]
@WebBreacher 
``
>>> in github.com/FortyNorthSecurity/EyeWitness/issues/530
>>>def get_ua_value (cycle_value):  while ["CALL"]  then
throw, ERROR "UserAgent Cycling Function disabled."
``

**Comment by Relkci** [comment]
#446 support for cycling was removed

I could see the value in taking a screenshot of a single webservice may times with different UAs.   Though... I'd never use it.  

My suggestion is to remove the remnant artifacts code.  If/when someone wishes to make many screenshots of a single site with different UA-- or many screenshots of many sites with different UAs-- they can just loop it in a bash script and pass a static UA that's rotated through. 

something this untested code: 

```bash
#!/bin/bash
input="/path/to/txt/file/of/UA-lists"
while read -r line
do
   python3 Eyewitness.py -f hosts -d report-$line  --no-clear --no-prompt --user-agent "$line"
done < "$input"
```

**Comment by digininja** [comment]
I doubt I'd ever use it either.

This method would work, but you'd end up with loads of reports, would it be
useful to add a way to have a report merged into an existing one rather
then the current option of just overwriting it? That is something I'd use,
not often, but if I'm scanning multiple subnets I'll have an XML file for
each, but want a single EW report at the end of it.

**Comment by Relkci** [comment]
That seems reasonable -- in theory it would just be the merge of sql database contents that is used for reporting.  Maybe make a new issue for feature suggestion.
