### ISSUE TITLE
Report doesn't load without internet connection - bootstrap

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#533]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu - Burp's built in browser

## Expected behavior (vs. what you encountered)
Report should load in browser all the time

Report doesn't load in the browser if you don't have an internet connection as it tries to pull this file from the CDN:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

Firefox is fine, but Burp's built in Chromium loads the headers for page one then sits spinning waiting for the CSS file to load.

I grabbed a local copy of the file, changed to that and it then loaded fine.

## Any additional information

Niche use case, but may be worth using a local copy of the CSS file rather than the CDN version as you've got everything else local.

**Comment by digininja** [comment]
Just in case anyone gets to this before it is sorted out, this will change the loading from CDN to local:

```
perl -p -i -e "s#https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css##" *html
```

You then just need to download the CSS file to the same directory as the reports:

```
wget https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
```

**Comment by ChrisTruncer** [comment]
Yeah, this is something we should add in, agreed,

**Comment by digininja** [comment]
Lazy, lazy!
