### ISSUE TITLE
Error: Service geckodriver unexpectedly exited. Status code was: 64

### ISSUE THREAD

**Issue by anishnaik** [RedSiege/EyeWitness#543]
Hello,
I am trying to run EyeWitness on my MacBook using **Docker Engine** and am getting an error with geckodriver.

# OS and Docker Engine details
## OS details
OS: MacOSX Big Sur (v11.6)
Architecture: x86-64

## Docker Engine details
Docker Engine version: 20.10.8
Docker Engine OSType: linux
Docker Engine Architecture: x86_64

# Docker Build
`docker build --build-arg user=eyewitness --tag eyewitness --file /Users/---/Documents/---/compose/Dockerfile `.

# Docker Run
`docker run --rm -it -v /Users/---/Documents/---/assets/download:/tmp/EyeWitness eyewitness --web --single http://www.google.com`

# Error I got
```
Attempting to screenshot http://www.google.com
Message: Service geckodriver unexpectedly exited. Status code was: 64
```

According to the some documentation I found [here](https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD%204.3-RELEASE&format=html), **status code 64** means that "The command was used incorrectly, e.g., with the wrong number of arguments, a bad flag, a bad syntax in a parameter, or whatever."

# Additional info
I pulled the latest from master after the fix for selenium's `firefox_options`. I am assuming that that change is leading to maybe some webdriver issues? Since this is 'Docker-ized' I don't think there is any issue with my OS configuration?

Thanks for the help!

**Comment by joeemurphy** [comment]
I was getting this same error when installing from master using the setup.sh script (not docker). I was able to resolve it by downloading the latest geckdriver from here: https://github.com/mozilla/geckodriver/releases

To install, I just did this:

- tar -xvzf geckodriver*
- chmod +x geckodriver
- mv geckodriver /usr/local/bin/

I'm not sure if that will be helpful at all for docker installations though

**Comment by medxpy** [comment]
@joeemurphy i did the steps you mentioned above but it's not work.

**Comment by vansh1** [comment]
its still not solved i tried everything mentioned above still same issue please help him
