### ISSUE TITLE
Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by israsec** [RedSiege/EyeWitness#544]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux Release 2021.2

## Expected behavior (vs. what you encountered)
To screenshot subdomains

## Any additional information
I installed the most recent release from the github repo and setup.sh script. 
I encountered an error message of :
Error: Service geckodriver unexpectedly exited. Status code was: 64

This was fixed with with @joeemurphy 's suggestion from issue #543 to wget the newest geckodriver.

After installing the driver I am still facing an error of:
 **"Message: Process unexpectedly closed with status 1"**
This is not the issue from #514 as I am attempting against www.google.com

Thanks for the help :)

**Comment by vansh1** [comment]
@israsec same error  dude, please let me know if you got any solution of it

**Comment by DhiralGit** [comment]
same error! any solution?

**Comment by sarparm** [comment]
Any solutions for this error?
I am having the same issue

**Comment by iamcobolt** [comment]
If you're running as root, use "sudo -i" to run FireFox can't be run as root.

**Comment by Olusmith8** [comment]
i tried your recommended solution is still the same thing I have even tried to restore my VM maybe it the cause still not solved

**Comment by KaiZenSec** [comment]
Same issue on fresh Kali 2022.3

**Comment by Relkci** [comment]
Is this an ongoing issue?  If not, will close.

**Comment by Parveen-Birthaliya** [comment]
same issue
