### ISSUE TITLE
Web request failed to parse

### ISSUE THREAD

**Issue by phanthom0** [RedSiege/EyeWitness#548]
## OS Used - ALL Information (architecture, linux flavor, etc.)

- Linux MAX 5.14.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

when I perform `eyewitness -f ipsTest.txt --web`  the tool fail, the result is:

![Screenshot from 2021-12-05 13-37-57](https://user-images.githubusercontent.com/8546865/144735479-3e0a2015-5303-4a65-99b0-60b422f6952c.png)

As you can see there is an error "fail to parse" the web request.

the content of the file  ipsTest.txt
![Screenshot from 2021-12-05 13-37-45](https://user-images.githubusercontent.com/8546865/144735518-ca5947d1-5b56-4cac-91a0-afbef8f4c857.png)

## Expected behavior (vs. what you encountered)

The expected behavior is to scan the host, and generate the report, but as you can see, wasn't possible.

## Any additional information

even if I change the parameters, i encounter the same error

**Comment by Relkci** [comment]
Please try after the updated setup script has been committed.  Re-open if you still have issues and include a sample from iptsTest.txt please.
