### ISSUE TITLE
Prevent terminal screen buffer from being cleared when running application

### ISSUE THREAD

**Issue by denevin** [RedSiege/EyeWitness#552]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux

## Expected behavior (vs. what you encountered)
When running eyewitness, the terminal screen buffer is cleared and all the information that was there previously is lost.
During pentesting, previous information that was in the terminal screen buffer before might have not been saved yet.
It would be great if the eyewitness application does not clear the terminal screen buffer when it's started and instead keeps information that was previously there so that it's possible to scroll up in the terminal screen to retried information from other applications that were ran before eyewitness.

**Comment by n00py** [comment]
#456 also.

**Comment by sneakerhax** [comment]
I would also be interested in seeing an argument added to avoid clearing the screen upon execution. When you're running this with automation, especially inside a container the earlier stages of the automation output are cleared.

**Comment by Relkci** [comment]
@ChrisTruncer -- running #647 past you for your opinion.  Rather than always clearing like in #559 , this MR passes as an optional argument, with the default being a screen clear to your preference

**Comment by ChrisTruncer** [comment]
Thank you for highlighting this, and apologies for the business as of late. For what its worth, the proposed addition for not clearing the screen by having a CLI flag looks solid. I'm good with that.

**Comment by 0x6d6f7468** [comment]
Maybe this is me being dumb, but I've always wondered what the point of clearing the buffer automatically was.

For what it's worth, I would probably prefer _not_ clearing to be default, but at that point I wonder if it would be better to just remove the feature altogether and leave that up to the user via the `clear` command, rather than adding another command line argument. Just my $0.02

**Comment by ChrisTruncer** [comment]
When this was first being developed, I preferred it to do that, and still largely do, so that's why. But I don't mind the inclusion of an easy to add cli parameter that changes that
