### ISSUE TITLE
Unable to run Eyewitness on Zorin 16 Pro

### ISSUE THREAD

**Issue by SRZEUS1990** [RedSiege/EyeWitness#553]
## OS Used - ALL Information (architecture, linux flavor, etc.)
**Zorin 16 Pro**

## Pastebin link to error you are encountering
![Zorin](https://user-images.githubusercontent.com/96624181/149832011-0adc006e-04f3-4412-9195-626cc74d35f8.png)

[Error]: Zorin is not supported by this setup script.

## Any additional information
cd Python/setup/
sudo ./setup.sh

**Comment by 0x6d6f7468** [comment]
Hi @SRZEUS1990. This is a pretty old issue, so I wanted to touch base with you and ask if Zorin support is still something you're hurting for.

I'm not familiar with Zorin so I'll have to download the free version and take a look. Let me know and I'll look at it when I get some time, probably after the next round of

**Comment by SRZEUS1990** [comment]
> Hi @SRZEUS1990. This is a pretty old issue, so I wanted to touch base with you and ask if Zorin support is still something you're hurting for.
> 
> I'm not familiar with Zorin so I'll have to download the free version and take a look. Let me know and I'll look at it when I get some time, probably after the next round of

Hello,

I’m no longer using Zorin OS . Looks like it’s working fine for mint.

**Comment by 0x6d6f7468** [comment]
Ok, thanks for confirming. I think I'm going to close this issue then. We can revisit this in the future if we get more requests for Zorin support.

Thanks!
