### ISSUE TITLE
Open-ports.csv just show port 80

### ISSUE THREAD

**Issue by Hennard** [RedSiege/EyeWitness#558]
Hi,

How can I get the open_ports.csv report to show 443 ports that are open? Now it just shows port 80 in the report.

My scan string:  EyeWitness.py --web -f /home/user/Documents/url-list/url-OUT.text --timeout 30 --prepend-https

Thanks.

**Comment by Relkci** [comment]
Can't reproduce with current codebase. Were screenshots taken from 443 (was there a tls/cert issue?)  -- may also have been fixed with recent code changes

![image](https://github.com/RedSiege/EyeWitness/assets/29710634/bbb71df8-5fe6-41d9-bbe0-178c3b57d0f5)
