### ISSUE TITLE
sqlite3: database locked: Output to Remote SMB Share

### ISSUE THREAD

**Issue by Zamanry** [RedSiege/EyeWitness#561]
## OS Used - ALL Information (architecture, linux flavor, etc.)
- Kali Linux rolling 2022.1 x64
- See the `lsb_release -a` command in the text file below

## Pastebin link to error you are encountering
Pastebin found my code as inappropriate. No idea why. So I attached the file instead. Let me know if you need anymore context.
- [EyeWitness_sqlite3_Error.txt](https://github.com/FortyNorthSecurity/EyeWitness/files/8215710/EyeWitness_sqlite3_Error.txt)

## Expected behavior (vs. what you encountered)
SMBv3 remote file shares are supported.

## Any additional information
No other tools are running. The system was rebooted just before running. I cannot find an EyeWitness version identifier in the help screen to provide. EyeWitness was installed via APT and not GitHub.

**Comment by Relkci** [comment]
SQLite is not reliable on SMB/NFS due to file locking mechanics.  Possible work around will be to run on local storage and then copy to the SMB mount after the report is generated.  This isn't an issue with EyeWitness codebase, but the nature of SMB file locks over SMB.
