### ISSUE TITLE
Eyewitness hangs on "connection refused" error and never completes.

### ISSUE THREAD

**Issue by TheEthicalHackingGuru** [RedSiege/EyeWitness#565]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux 

## Expected behavior (vs. what you encountered)
Eyewitness hangs on "connection refused" error and never completes.

## Any additional information
Eyewitness hangs on "connection refused" error and never completes. Is there an option to skip over connection refused responses and finish scanning all the URLs?

**Comment by tr4cefl0w** [comment]
Same issue here.
