### ISSUE TITLE
Error: ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by stashudoy** [RedSiege/EyeWitness#574]
when run  in kali linux by python 2.7.18:

kali> ./EyeWitness.py -f urls.txt

 i have message:  Error: ModuleNotFoundError: No module named '_sqlite3' :(

How can i fix it? Thank you!

**Comment by Relkci** [comment]
prior updates corrected /w use of python3, run EyeWitness/Python/setup/setup.sh

recommend issue be closed
