### ISSUE TITLE
The browser option parameter firefox_options was deprecated in Selenium 3.8.0

### ISSUE THREAD

**Issue by 0xVIC** [RedSiege/EyeWitness#581]
## OS Used: Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux

```
WebDriver.__init__() got an unexpected keyword argument 'firefox_options'
WebDriver.__init__() got an unexpected keyword argument 'firefox_options'
WebDriver.__init__() got an unexpected keyword argument 'firefox_options'
WebDriver.__init__() got an unexpected keyword argument 'firefox_options'
WebDriver.__init__() got an unexpected keyword argument 'firefox_options'
Finished in 0.1722273826599121 seconds
```
REF: https://stackoverflow.com/questions/70326002/typeerror-webdriver-init-got-an-unexpected-keyword-argument-firefox-opti

**Comment by Relkci** [comment]
working on 
Linux kali 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-04-09) x86_64 GNU/Linux
selenium                       4.9.1
please re-open if this is still an issue
