### ISSUE TITLE
Issues with https when launched via python subprocess

### ISSUE THREAD

**Issue by githule** [RedSiege/EyeWitness#583]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Docker image based on a fork of the Dockerfile available on this repo.

## Error you are encountering

I am trying to do some automation to interact with our tools.

- When job is ran from bash cli or bash cli inside docker : it works as expected.
- When job is ran from a python subprocess.run() method with a cli such as `python3 Python/EyeWitness.py --no-prompt --web --single https://www.google.com`,  I got  **WebDriverError** on https but it works fine for unsecured http// urls.

I tried Popen method and Run method of the subprocess package and to force passing of environnement variable without success.
I think that it is tied to certificates repository or environnemental issue

I know it's probably not an issue on your codebase but more something about how Popen handles its processes.

_Do you have an idea of what is missing and where to investigate (logs, verbosity)?_

I precise I reviewed the few issues about  de WebDriverError but couldn't see any relation with this one.

Thanks for you help and this wonderfull tool.

**Comment by githule** [comment]
This issue is solved but I don't know why.
If possible, before closing, can you provide elements on where to investigate ?

**Comment by Relkci** [comment]
Going to close this, but thought I'd point some direction incase anyone ends up here again.

Double check user context that the sub-process will run with-in.  It sounds like the certificate repo isn't available to the sub-process and causing the sites to fail loading, or possibly a parameter was not passed through environment variables.
