### ISSUE TITLE
ERROR: Try again, or see if Github is blocked?

### ISSUE THREAD

**Issue by Explore-c** [RedSiege/EyeWitness#588]
## OS Used - ALL Information (architecture, linux flavor, etc.)

windows
## Pastebin link to error you are encountering
www.baidu.com

## Expected behavior (vs. what you encountered)
![image](https://user-images.githubusercontent.com/46821530/199937872-367158a5-e160-4130-9b2e-90c2fee06009.png)

**Comment by digininja** [comment]
Is GitHub blocked?

**Comment by Relkci** [comment]
build off current master, seemed to work fine.  likely isolated issue.  

![image](https://user-images.githubusercontent.com/29710634/200095790-4159359d-d443-43c1-9ee4-3e02efe6c8a2.png)

issue likely can be closed
