### ISSUE TITLE
crash on start (kali)

### ISSUE THREAD

**Issue by RandonDude** [RedSiege/EyeWitness#601]
## OS Used - ALL Information (architecture, linux flavor, etc.)
fresh installation of linux kali 

## Pastebin link to error you are encountering
Error: https://pastebin.com/1yRJ2phS

Gecko Log: https://pastebin.com/9T9yyJZM

## Expected behavior (vs. what you encountered)
crashed at start but expected to work :D

## Any additional information
newest firefox installation

**Comment by Zamanry** [comment]
I fixed this through installing the latest geckodriver following the guide from here:
- https://stackoverflow.com/questions/40867959/installing-geckodriver-only-using-terminal
- https://github.com/mozilla/geckodriver/releases

*I could be wrong,* but a related GitHub issue could be here:
- https://github.com/mozilla/geckodriver/issues/1959
