### ISSUE TITLE
Message: Failed to read marionette port

### ISSUE THREAD

**Issue by Bozx** [RedSiege/EyeWitness#604]
![image](https://user-images.githubusercontent.com/38514671/209608915-adb23474-c32e-442f-8639-0f41bdae5205.png)

I am getting this error all the time. I have installed all the modules on pip and other requirements both manually and both automatically with setup.sh with root privileges.
What should I do?
Kind regards.

**Comment by reconnization** [comment]
Same here, it's an unpatched bug. ¯\_(ツ)_/¯

_[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt_

**Comment by reconnization** [comment]
Apparently the developers ignored this issue and responded to me within 5 minutes in a very nice way:
https://github.com/FortyNorthSecurity/EyeWitness/issues/606
xD
