### ISSUE TITLE
Error from netaddr on Python app startup

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#611]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Up to date Kali

## Issue
I'm reporting this as a non-issue in case anyone else sees it and worries....

I've got a fully updated Kali install and when I start EW the following error appears on screen for a split second before being removed as the screen is cleared.

```
/usr/lib/python3/dist-packages/netaddr/strategy/__init__.py:189: SyntaxWarning: "is nog" with a literal. Did you mean "!="?
 if word_setp is not '':
```

This is a problem with the netaddr package, not EW, and does not appear to affect EW in any way.

**Comment by ChrisTruncer** [comment]
Always finding issues in libraries that I use :)

**Comment by 0x6d6f7468** [comment]
Looking at my current VM, I have netaddr version `0.8.0` and I think this issue has been fixed. The previously offending code now reads:

```python
    if word_sep != '':
        #   Check custom separator.
        if not _is_str(word_sep):
            raise ValueError('word separator is not a string: %r!' % (word_sep,))
```
We might be good to close this issue, but I'll wait for @digininja to decide.

**Comment by digininja** [comment]
I've not seen the issue for ages so happy to close it.

I only reported it so if anyone else saw it they wouldn't panic and report
it as a critical problem.

**Comment by 0x6d6f7468** [comment]
Ok cool. I'll consider this resolved and direct anybody here on the off chance that it comes up again.

Closing. Thanks.
