### ISSUE TITLE
Getting chromedriver errors on a fresh install

### ISSUE THREAD

**Issue by Viss** [RedSiege/EyeWitness#614]
ubuntu 22.10, on a DO droplet.
Freshly installed out of git this morning (tuesday jun 27)

Getting this error when trying to do --single:

```
WebDriver.__init__() got an unexpected keyword argument 'capabilities'
```

Seems like its a syntax thing in python with how selenium is being called? I tried to tackle it myself and just made it worse ;b

**Comment by Viss** [comment]
Looks like its any selenium call, not just --single

<img width="567" alt="image" src="https://github.com/RedSiege/EyeWitness/assets/1756255/38301550-edd5-4706-a12c-c3387469ef7e">

**Comment by omespino** [comment]
Hey, I had a full working Eyewitness installation in DO droplet too and it was working just fine, but once I installed google cloud cli, it broke Eyewitness (it seems that gcp cli forces a specific python3.X version), anyway, I purged python3.x in my DO droplet

```
sudo apt purge python* 
```

then I remove Eyewitnes and git clone from the main/master branch, then

```
git clone https://github.com/RedSiege/EyeWitness.git
cd EyeWitness/Python/setup/
sudo ./setup.sh
```

and worked like a charm

**Comment by Relkci** [comment]
This appears to have been resolved.  If you're still running into issues after the driver and setup code changes, please re-open a new issue.
