### ISSUE TITLE
Receiving error WebDriver.__init__() got an unexpected keyword argument 'capabilities'

### ISSUE THREAD

**Issue by john-7777** [RedSiege/EyeWitness#617]
## OS Used - ALL Information (architecture, linux flavor, etc.)
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2023.1"
VERSION_ID="2023.1"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

## Pastebin link to error you are encountering
![image](https://github.com/RedSiege/EyeWitness/assets/86320007/a8db8b7e-f09f-4d94-a86d-f9a364021ddc)

## Expected behavior (vs. what you encountered)
Couple of days before the tool after fresh install was working perfectly fine but now its throwing error, i tried installing it so many times but still, the error persists.

**Comment by sl2mmin** [comment]
same here

**Comment by sl2mmin** [comment]
Looks like the issue started with selenium version 4.10.0. Downgrading it to 4.9.1 works helps for now.

```
pip install selenium==4.9.1
```

**Comment by FlyingPhish** [comment]
Same issue, need to modify 'python3 -m pip install selenium --upgrade' in the setup file to `pip install selenium==4.9.1` as stated by @sl2mmin

**Comment by ChrisTruncer** [comment]
This should now be fixed in the setup script, right now it's hard coding the version of selenium to use

**Comment by Sajon12-ux** [comment]
same issue help  me
![Uploading issue.PNG…]()

**Comment by Sajon12-ux** [comment]
same issue help  me
![issue](https://github.com/user-attachments/assets/3145e84c-1614-4b70-8e29-31dcc02544f4)
