### ISSUE TITLE
Dockerfile: invalid base image tag

### ISSUE THREAD

**Issue by v-p-b** [RedSiege/EyeWitness#618]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Debian 11

## Pastebin link to error you are encountering

```
$ docker build --build-arg user=$USER --tag eyewitness --file ./Python/Dockerfile .
Sending build context to Docker daemon  29.78MB
Step 1/10 : FROM phusion/baseimage:master-amd64
manifest for phusion/baseimage:master-amd64 not found: manifest unknown: manifest unknown
```

## Expected behavior (vs. what you encountered)

Image is build without errors

## Any additional information

The master-amd64 tag doesn't exist on DockerHub anymore.

**Comment by 0x6d6f7468** [comment]
Hey @v-p-b, just wanted to circle back on this and see if you've had any more issues since PR #634 was merged. The PR didn't indicate that it closed this issue so I wanted to check. Thanks.

**Comment by v-p-b** [comment]
Yup, this one fixes it, thanks for the heads up!
