### ISSUE TITLE
Don't create output directories before you know something will go in them

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#625]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux/Python version

## Error
```
./EyeWitness.py -x file_that_does_not_exist -d /tmp/output
```

The output directory structure is created in /tmp/output but never used because the XML file doesn't exist so the script doesn't run.

Running it a second time with an XML file that does exist (correcting the silly typo) means you now have to accept the "do you want to overwrite the directory" message.

## Expected behavior (vs. what you encountered)
Don't create the output directories till you know that you are going to use them.

## Any additional information
Marmite Cornettos may be a thing!

**Comment by ChrisTruncer** [comment]
Fixed just to let you know your additional information is incorrect!

**Comment by digininja** [comment]
It is correct, it just maybe should not be correct.
