### ISSUE TITLE
ctrl-c in single mode does not exit cleanly

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#632]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Latest version in Ubuntu

## Stuff
Hitting ctrl-c when using either `-f` or `-x` terminates the app nicely and shows the message on how to resume. Hitting it in single mode gives a stack trace.

## Expected behavior (vs. what you encountered)
You don't need a resume in single mode, but catching the ctrl-c and exiting gracefully would be nice.

## Any additional information
Gazing through windows,
Witness to life's fleeting scenes,
Eyes hold stories told.

**Comment by 0x6d6f7468** [comment]
Thanks for the suggestion, good call. We can copy the signal handler from multi mode into single mode pretty easily without too many adjustments. PR incoming shortly.
