### ISSUE TITLE
Simplfy setup of geckodriver

### ISSUE THREAD

**Issue by digininja** [RedSiege/EyeWitness#635]
In the Python setup script, you specify the two different architecture paths for the gecko driver at the top and then in each OS block chose which architecture to go with and then install it. What you could do is have a block like this at the top of the script so it is ran for every OS:

```
if [ ${MACHINE_TYPE} == 'x86_64' ]; then
  wget ${geckodriver_x86_64} -O geckodriver.tar.gz
else
  wget ${geckodriver_x86_32} -O geckodriver.tar.gz
fi
```
Then in the blocks you can get rid of the architecture checks and just install `geckodriver.tar.gz`. It would save having to update the version number in loads of places when you update the version.

**Comment by 0x6d6f7468** [comment]
This is something I'm working on addressing as part of a wider setup.sh rewrite/refactor, also including support for aarch64.

**Comment by 0x6d6f7468** [comment]
As promised (for once)
