### ISSUE TITLE
Eyewitness won't exit on windows

### ISSUE THREAD

**Issue by Lolo21-ui** [RedSiege/EyeWitness#638]
Eyewitness says finished exiting shortly! on windows for a long time and won't exit on windows after taking the screenshots.Please fix this issue. I am using the windows command prompt to run the tool.

**Comment by Relkci** [comment]
Seems to work ok on current build targeting 4.8.  

What command arguments did you use that caused the issue?  

![image](https://github.com/RedSiege/EyeWitness/assets/29710634/9f72dd6d-83fc-4b5a-8aa7-a48c8fa2c14f)

**Comment by Lolo21-ui** [comment]
Thanks for your help I was not providing the output directory to save the screenshots to i think that is the reason why it was not exiting.I wad only using this command argument:
Eyewitness.exe -f examplefile.txt and not Eyewitness.exe -f examplefile.txt -O C:/Screenshots -d 5.
I think we can close this issue.

**Comment by Lolo21-ui** [comment]
Thanks for your help I was not providing the output directory to save the screenshots to i think that is the reason why it was not exiting.I was only using this command argument:
Eyewitness.exe -f examplefile.txt and not Eyewitness.exe -f examplefile.txt -O C:/Screenshots -d 5.
I think we can close this issue.

**Comment by Relkci** [comment]
Reviewing -- I tried both with and without the -o and -d arguments and I couldn't get the process to fail to exit on its own either time.  I'm not sure what the original cause was -- but I suspect it was something environmental at the time  ? (network connection on one of the hosts where a thread did not finish screenshot, or something?).  I'm not really sure as I couldn't reproduce.  Re-open if this happens again.  thanks!
