### ISSUE TITLE
Malformed URL

### ISSUE THREAD

**Issue by Talanor** [RedSiege/EyeWitness#656]
Everything is detailed in an un-merged PR : https://github.com/RedSiege/EyeWitness/pull/605

Is this something that would be merged eventually if a new PR was opened ?
Would you also merge a fix to continue grabbing other URLs if a legitimately malformed URL existed in the URL file  ?

**Comment by Relkci** [comment]
Yes.  Out of curiosity though, is the issue persistent if you URL encode?
