### ISSUE TITLE
Infinitely loading after showing "Attempting to screenshot https://courses.tesla.com"

### ISSUE THREAD

**Issue by crazymonk007** [RedSiege/EyeWitness#657]
I am using AWS EC2 instance with Kali OS.

Instead of clicking screenshots, eyewitness kept loading infinitely, after the line "Attempting to screenshot https://courses.tesla.com"

Here is a screenshot of the issue i am facing.

<img width="450" alt="Untitled" src="https://github.com/RedSiege/EyeWitness/assets/137065986/0dd560ee-ffd6-4018-9101-026eebad485a">

**Comment by Relkci** [comment]
Did you install from the Github repo or the kali apt package?

![image](https://github.com/RedSiege/EyeWitness/assets/29710634/464de5fd-6bf9-4fb6-93a2-5075b9bc2b57)

**Comment by crazymonk007** [comment]
> Did you install from the Github repo or the kali apt package?
> 
> Screenshot below is from current-ish Kali image + EyeWitness installed from GitHub repo.
> 
> ![image](https://private-user-images.githubusercontent.com/29710634/335941423-464de5fd-6bf9-4fb6-93a2-5075b9bc2b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjM2NTEsIm5iZiI6MTcxNzQyMzM1MSwicGF0aCI6Ii8yOTcxMDYzNC8zMzU5NDE0MjMtNDY0ZGU1ZmQtNmJmOS00ZmI2LTkzYTItNTA3NWI5YmMyYjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE0MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjEzYzg1MDIxZTJiNmUwNWM3YzdiZTc4YWIzNDg4YTM5YTk4NGQ5ZmQzNGQzYzQzYThlYzExM2VhYzVjYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jkDljeE-n6Zju69X4H47jzdRpNRG5IMD5_F3RIyNrI)

Its working now, thanx
