### ISSUE TITLE
Documentation Link Certificate Expired

### ISSUE THREAD

**Issue by svetterIO** [RedSiege/EyeWitness#666]
For the mentioned documentation link (https://www.christophertruncer.com/eyewitness-2-0-release-and-user-guide/) browser presents Error code: [SEC_ERROR_EXPIRED_CERTIFICATE] - The certificate for www.christophertruncer.com expired on 27/04/2024.

Therefore documentation can't be accessed. Please fix.

**Comment by digininja** [comment]
I've messaged @ChrisTruncer to let him know.

The documentation can still be accessed, you just have to accept the expired certificate.

**Comment by 0x6d6f7468** [comment]
It would perhaps be worth considering taking whatever documentation Chris has and migrating it to the Wiki section of this repo, if he would be interested in doing that.

**Comment by ChrisTruncer** [comment]
I've finally updated the certificate :)
