### ISSUE TITLE
not showing more results or maybe not working 

### ISSUE THREAD

**Issue by ImYasine** [RedSiege/EyeWitness#682]
![Screenshot 2024-08-21 201021](https://github.com/user-attachments/assets/4b430838-086a-4924-bfa3-db397285b2a9)
After running eyewitness it maybe stops or not showing any result this couldn't be a internet issue or system issue because I'm using cloud machine appreciate for your answer or solution

**Comment by Relkci** [comment]
Are you on the most recent version of EW from github?  We tweaked some timeout handling awhile back.
